LanchesOnline/Models/Carrinho de compra/CarrinhoCompra.cs
using LanchesOnline.Context;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;

namespace LanchesOnline.Models {
    public class CarrinhoCompra {
        private readonly LanchesOnlineContext _db;

        public CarrinhoCompra(LanchesOnlineContext db) {
            _db = db;
        }

        public string Id { get; set; }
        public List<ItemCarrinhoCompra> Itens { get; set; }

        public static CarrinhoCompra ObterCarrinhoCompra(IServiceProvider services) {
            // Define uma sessão acessendo o contexto atual.
            var session = services
                .GetRequiredService<IHttpContextAccessor>()?
                .HttpContext
                .Session;

            // Obtém um servico do tipo do nosso contexto.
            var db = services.GetService<LanchesOnlineContext>();

            // Obtém ou gera o id do carrinho.
            var idCarrinhoCompra = session.GetString("IdCarrinhoCompra") ?? Guid.NewGuid().ToString();

            // Atribui o id do carrinho na Sessão.
            session.SetString("IdCarrinhoCompra", idCarrinhoCompra);

            return new CarrinhoCompra(db) {
                Id = idCarrinhoCompra
            };
        }

        public void AdicionarItem(Lanche lanche, int quantidade) {
            var lancheNaoExiste = lanche == null;
            if (lancheNaoExiste) {
                return;
            }

            var itemCarrinho = _db.ItensCarrinhosCompras
                .SingleOrDefault(item => item.IdLanche == lanche.Id && item.IdCarrinhoCompra == Id);

            var itemNaoExiste = itemCarrinho == null;
            if (itemNaoExiste) {
                incluir();
            } else {
                aumentarQuantidade();
            }

            _db.SaveChanges();

            void incluir() {
                _db.ItensCarrinhosCompras.Add(new ItemCarrinhoCompra {
                    IdCarrinhoCompra = Id,
                    Lanche = lanche,
                    Quantidade = 1
                });
            }

            void aumentarQuantidade() {
                itemCarrinho.Quantidade++;
            }
        }

        public int RemoverItem(Lanche lanche) {
            var lancheNaoExiste = lanche == null;
            if (lancheNaoExiste) {
                return 0;
            }

            var itemCarrinho = _db.ItensCarrinhosCompras
                .SingleOrDefault(item => item.IdLanche == lanche.Id && item.IdCarrinhoCompra == Id);

            var quantidadeRetorno = 0;

            var itemExiste = itemCarrinho != null;
            if (itemExiste) {
                var possuiQuantidade = itemCarrinho.Quantidade > 1;
                if (possuiQuantidade) {
                    reduzirQuantidade();
                } else {
                    excluir();
                }
            }

            _db.SaveChanges();

            return quantidadeRetorno;

            void reduzirQuantidade() {
                itemCarrinho.Quantidade--;
                quantidadeRetorno = itemCarrinho.Quantidade;
            }

            void excluir() {
                _db.ItensCarrinhosCompras.Remove(itemCarrinho);
            }
        }   

        public List<ItemCarrinhoCompra> ObterListaItens() {
            return Itens ??= _db.ItensCarrinhosCompras
                .Where(item => item.IdCarrinhoCompra == Id)
                .Include(item => item.Lanche)
                .ToList();
        }

        public void LimparItens() {
            var itensCarrinho = _db.ItensCarrinhosCompras
                .Where(item => item.IdCarrinhoCompra == Id)
                .ToArray();

            _db.ItensCarrinhosCompras.RemoveRange(itensCarrinho);

            _db.SaveChanges();
        }

        public decimal ObterValorTotal() {
            return _db.ItensCarrinhosCompras
                .Where(item => item.IdCarrinhoCompra == Id)
                .Sum(item => item.Lanche.Preco * item.Quantidade);
        }
    }
}

LanchesOnline/ViewModels/CarrinhoCompra/CarrinhoCompraViewModel.cs
using LanchesOnline.Models;

namespace LanchesOnline.ViewModels {
    public class CarrinhoCompraViewModel {
        public CarrinhoCompra CarrinhoCompra { get; set; }
        public decimal ValorTotal { get; set; }
    }
}

LanchesOnline/Controllers/CarrinhoCompraController.cs
using LanchesOnline.Models;
using LanchesOnline.Repositories.Interfaces;
using LanchesOnline.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace LanchesOnline.Controllers {
    public class CarrinhoCompraController : Controller {
        private readonly ILancheRepository _lancheRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(ILancheRepository lancheRepository, CarrinhoCompra carrinhoCompra) {
            _lancheRepository = lancheRepository;
            _carrinhoCompra = carrinhoCompra;
        }

        public IActionResult Index() {
            var itens = _carrinhoCompra.ObterListaItens();
            _carrinhoCompra.Itens = itens;

            return View(new CarrinhoCompraViewModel {
                CarrinhoCompra = _carrinhoCompra,
                ValorTotal = _carrinhoCompra.ObterValorTotal()
            });
        }

        public RedirectToActionResult AdicionarItem(int idLanche) {
            var lancheAdicionar = _lancheRepository
                .Lanches
                .FirstOrDefault(lanche => lanche.Id == idLanche);

            _carrinhoCompra.AdicionarItem(lancheAdicionar, 1);

            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoverItem(int idLanche) {
            var lancheRemover = _lancheRepository
                .Lanches
                .FirstOrDefault(lanche => lanche.Id == idLanche);

            _carrinhoCompra.RemoverItem(lancheRemover);

            return RedirectToAction("Index");
        }
    }
}

LanchesOnline/Controllers/LancheController.cs
using LanchesOnline.Repositories.Interfaces;
using LanchesOnline.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LanchesOnline.Controllers {
    public class LancheController : Controller {
        private readonly ILancheRepository _lancheRepository;
        private readonly ICategoriaLancheRepository _cagegoriaRepository;

        public LancheController(ILancheRepository lancheRepository, ICategoriaLancheRepository cagegoriaRepository) {
            _lancheRepository = lancheRepository;
            _cagegoriaRepository = cagegoriaRepository;
        }

        public IActionResult List() {
            //ViewBag.Lanche = "Lanches";
            //ViewData["Categoria"] = "Categoria";

            return View(new LancheListViewModel {
                Categoria = "Categoria atual",
                Lanches = _lancheRepository.Lanches
            });
        }
    }
}

LanchesOnline/Views/CarrinhoCompra/Index.cshtml
@model CarrinhoCompraViewModel
<div class="row form-check">
    <h2>Seu carrinho de compras</h2>
    <h4>Aqui estão os seus pedidos</h4>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Quantidade</th>
                <th>Lanche</th>
                <th class="text-right">Preço</th>
                <th class="text-right">Subtotal</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.CarrinhoCompra.Itens) {
                <tr>
                    <td class="text-center">@item.Quantidade</td>
                    <td class="text-center">@item.Lanche.Nome</td>
                    <td class="text-center">@item.Lanche.Preco.ToString("c")</td>
                    <td class="text-center">@((@item.Lanche.Preco * @item.Quantidade).ToString("c"))</td>
                    <td class="text-center"><a class="text-danger remove" href="#">content</a></td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">@Model.ValorTotal.ToString("c")</td>
            </tr>
        </tfoot>
    </table>
    <div class="text-right">
        <div class="btn-group">
            <a class="btn btn-success" asp-controller="Pedido" asp-action="Checkout">Encerrar pedido</a>
            <a class="btn-group">
                <a class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Adicionar mais lanches<span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a asp-controller="Lanche" asp-action="List" asp-route-categoria="Normal">Normal</a></li>
                    <li><a asp-controller="Lanche" asp-action="List" asp-route-categoria="Natural">Natural</a></li>
                </ul>
            </a>
        </div>
    </div>
</div>